name: kapdabazzarsellers
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.4
  firebase_auth: ^0.15.5+2
  google_fonts: ^0.3.9
  cupertino_icons: ^0.1.3
  scoped_model: ^1.0.1
  http: ^0.12.0+4
  shared_preferences: ^0.5.6+1
  rxdart: ^0.23.1
  flare_flutter: ^2.0.1
  flutter_shimmer: ^1.2.0
  firebase_storage:
  file_picker: ^1.5.0+2
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  
  uses-material-design: true
  assets:
    - assets/
